### PR TITLE
Move input arguments over to specifying both input and output dirs 

### PR DESCRIPTION
**Pull request by danikam**
Suggested update would match the format in https://github.com/hsf-training/hsf-training-cms-analysis/blob/master/histograms.sh

### CODE REVIEW

**Comment by klieret** [comment]
Hi @danikam : Thanks a lot for your PR! Apparently this flew under our radar, so sorry for replying only now.

It's nice to make this consistent, the only issue I have is that if people follow the video from the docker lesson, their command won't work. And it doesn't seem important enough to risk that.

But how about we take the best of both world and if only one argument is given, it's used for both and if two are given they are used as you have it here?

**Comment by danikam** [comment]
Hi @klieret, thanks for your review and suggestion! That sounds like a great idea - I've updated the PR to use the first argument for both input and output dir unless a second argument is provided. Please let me know if it's looking ok with the update!

**Review by klieret — APPROVED** [review]
Looking good, thanks a lot! :smiley:     (of course it would be even better to throw a warning in case 0 or more than 2 arguments are given though -- I leave it up to you if you want to merge it like it is or add that)

**Comment by danikam** [comment]
Thanks for the suggestion @klieret! I've added the warnings you suggested (actually I implemented them as error messages which exit after printing usage instructions). Please let me know if the updated script looks ok to merge!

**Comment by klieret** [comment]
Looks awesome, thanks a lot :)

**Comment by danikam** [comment]
Sounds good, thanks for the review! Looks like I don't have write access to this repo, so please go ahead and merge if it's good to go!

**Pull request merged**
